### ISSUE TITLE
Exception using Vuzzer fuzzing tcpdump

### ISSUE THREAD

**Issue by JsHuang** [vusec/vuzzer#12]
While using Vuzzer fuzzing tcpdump using the command
```
python runfuzzer.py -s './bin/tcpdump -r %s' \
-i './datatemp/tcpdump/' \
-w './idafiles/tcpdump.pkl' \
-n './idafiles/tcpdump.names'
```
I got exceptions as below:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "runfuzzer.py", line 628, in main
    gau.prepareBBOffsets()
  File "/home/jshuang/vuzzer/gautils.py", line 523, in prepareBBOffsets
    tdata=pickle.load(tFD)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named __builtin__
```
How can I fix this? I did not encouter this problem with other test programs?
the tcpdump version is 4.5.1

**Comment by JsHuang** [comment]
Duplicate of #9
